[project]
name = "castersugar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pychromecast>=14.0.9",
    "flask>=3.1.0",
    "boto3>=1.35.0",
    "requests>=2.32.0",
]
